### ISSUE TITLE
Network error everytime

### ISSUE THREAD

**Issue by Incognito4nonymous** [alashow/datmusic#47]
Hey, so first of all your website is awesome, but secondly, since yesterday I'm facing an odd issue, every device I go on the website with gives me a Network Error, I updated nothing and they are just the devices I go by everyday... That error just popped in like that, even going as far as affecting the mobile app, any ideas where the problem could come from ?

**Comment by alashow** [comment]
It's fixed now.
Thanks for reporting.

**Comment by Incognito4nonymous** [comment]
U ROCK MAN !

**Comment by Incognito4nonymous** [comment]
Huh, I haven't tried for a week now so I can't tell, don't worry I'll report all of the issues I'll get.

**Comment by el-gonzo** [comment]
The Network Error is back for me, I get the 

`Failed to load resource: the server responded with a status of 500 ()` 

error message every time i try to make a custom search.

**Comment by Incognito4nonymous** [comment]
It's back can't download anything without that error again...

**Comment by Incognito4nonymous** [comment]
Erh, probably related too but now it's a 404 whatever track I wanna download...

**Comment by alashow** [comment]
Fixed it. Not related though.
